In [31]:
#vectorizacion recodar que son sistutir for por operaciones que se aplican directamente sobre arrays 

#con bucle forr
import numpy as np
import math
import matplotlib.pyplot as plt

def lento(n=1000):
  x = np.linspace(-1,1,n)
  y = np.linspace(-1,1,n)
  z = np.linspace(-1,1,n)


  for i, _y in enumerate(y):
    for j, _x in enumerate(x):
      z[i,j] = math.sqrt(_x**2 + _y**2)
  return x,y,z


  %time x, y, z = lento()  






In [38]:
###---------------ejemplo--------------######

import matplotlib.pyplot as plt

def plot(x,y,z):
  plt.contourf(x,y,z)
  plt.colorbar()                    
  plt.xlabel("x",fontsize="16")
  plt.ylabel("y",fontsize="16")
  plt.title("$z = \sqrt{x^2 + y^2}$", fontsize="16")
  plt.show()

plot(x,y,z)   

NameError: ignored

In [40]:
#vamo aplicar lo mismo pero con vectorizaciones


def rapido (n=1000):
  p = np.linspace(-1,1,n)
  x,y = np.meshgrid(p,p) #funcion para crear mallas
  z= np.sqrt(x**2 + y**2)
  return x,y,z



%time x, x, z = rapido()  


CPU times: user 11.9 ms, sys: 0 ns, total: 11.9 ms
Wall time: 20.2 ms


In [41]:
def plot(x,y,z):
  plt.contourf(x,y,z)
  plt.colorbar()
  plt.xlabel("x",fontsize="16")
  plt.ylabel("y", fontsize="16")
  plt.title("$z =  \sqrt{x^2 + y^2}$", fontsize="16")
  plt.show()



plot(x,y,z)  

NameError: ignored

In [43]:
a= np.array([[2.5,3.1,7],[10,11,12]])
a

array([[ 2.5,  3.1,  7. ],
       [10. , 11. , 12. ]])

In [44]:
#algunas funciones en numpy

for func in (np.abs, np.sqrt, np.exp, np.log, np.ceil, np.modf, np.isnan, np.cos):
  print("\n", func.__name__)
  print(func(a))


 absolute
[[ 2.5  3.1  7. ]
 [10.  11.  12. ]]

 sqrt
[[1.58113883 1.76068169 2.64575131]
 [3.16227766 3.31662479 3.46410162]]

 exp
[[1.21824940e+01 2.21979513e+01 1.09663316e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]

 log
[[0.91629073 1.13140211 1.94591015]
 [2.30258509 2.39789527 2.48490665]]

 ceil
[[ 3.  4.  7.]
 [10. 11. 12.]]

 modf
(array([[0.5, 0.1, 0. ],
       [0. , 0. , 0. ]]), array([[ 2.,  3.,  7.],
       [10., 11., 12.]]))

 isnan
[[False False False]
 [False False False]]

 cos
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


In [45]:
#algunas funciones estadisticas
for func in (a.min, a.max, a.sum, a.prod, a.std, a.std, a.var):
  print(func.__name__, "=", func())
  

min = 2.5
max = 12.0
sum = 45.6
prod = 71610.0
std = 3.7260345319566395
std = 3.7260345319566395
var = 13.883333333333333


In [46]:
#calcular valor mdio de cada columna
a.mean(axis=0) #calcula el valor medio de cada columna

array([6.25, 7.05, 9.5 ])

In [47]:
#sumando valores por filas
a.sum(axis=1) #por fila

array([12.6, 33. ])

broadcasting

In [ ]:
#se aplica cuando en arrasy se hacen operaciones mateamaticas donde sus dimensiones no encajna
#si dos arrays no tienen el mismo rango, entonce se añadira una dimension de 1 al principio del array con menor tango hasta que estos coincidan


In [48]:
a= np.arange(5).reshape(1,1,5)
a

array([[[0, 1, 2, 3, 4]]])

In [50]:
a.shape

(1, 1, 5)

In [51]:
b= np.arange(5)
b

array([0, 1, 2, 3, 4])

In [52]:
b.shape

(5,)

In [53]:
a+b #se puedo porque ha ido añadiendo dimensiones de una hasta coincidri y poder sumar

array([[[0, 2, 4, 6, 8]]])

In [ ]:
#segundo ragla// lo mismo de la primera pero ahoar en cualquier otra dimension

In [54]:
#ejemplo
a= np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
a.shape

(2, 3)

In [57]:
b= np.array([[100],[200]])
b

array([[100],
       [200]])

In [58]:
b.shape

(2, 1)

In [59]:
a+b

array([[100, 101, 102],
       [203, 204, 205]])

In [ ]:
#tercera regla si uno dos se realizan pero sigue igualmente sin coincidar la operacion no se puede llevar acabo