In [ ]:
import torch

'ejemplo de un tenser bidimensional'

x= torch.ones(5,3)
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
x= torch.randn(5,3,2)
print(x)

tensor([[[-1.9642, -1.2501],
         [ 1.2383,  1.3804],
         [ 0.0842, -0.9957]],

        [[-0.3738, -0.0642],
         [-1.3676,  2.0692],
         [-0.0456, -0.0772]],

        [[-0.3342,  3.3606],
         [ 1.4495,  0.1431],
         [ 0.6799,  1.2048]],

        [[-0.6747,  1.4085],
         [ 1.1638,  0.0108],
         [ 0.9210,  0.2559]],

        [[-0.7150,  0.3495],
         [ 1.0777, -0.4106],
         [ 0.4102, -0.1516]]])


In [ ]:
'tranforma un array desde una lista'
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
x= torch.from_numpy(a)

print(x)


tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
'operaciones'

x= torch.rand(3,3)
y= torch.rand(3,3)


x,y

(tensor([[0.0132, 0.2502, 0.7739],
         [0.2525, 0.4734, 0.7121],
         [0.0961, 0.8031, 0.9265]]), tensor([[0.1872, 0.5062, 0.1869],
         [0.7419, 0.5995, 0.7288],
         [0.0332, 0.8974, 0.5773]]))

In [ ]:
print(x+y)

tensor([[0.2004, 0.7564, 0.9608],
        [0.9944, 1.0729, 1.4409],
        [0.1293, 1.7005, 1.5038]])


In [ ]:
t = torch.tensor(x+y) 'improvisando'
print(t)

tensor([[0.2004, 0.7564, 0.9608],
        [0.9944, 1.0729, 1.4409],
        [0.1293, 1.7005, 1.5038]])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


In [ ]:
'indexando'
t[0]
t[0,1]

tensor(0.7564)

In [ ]:
'indenxando sacando toda una columna'

x[0,:]
x[1,:]
x[2,:]

tensor([0.0132, 0.2502, 0.7739])

In [ ]:
'exeptualizando'
t[:-1, 1:] 'todas las filas menos la ultima y todas las columnas menos las ultimas' 

tensor([[0.7564, 0.9608],
        [1.0729, 1.4409]])

In [ ]:
'añadimos una dimension extra'
x.view(1,3,3).shape   #una matris 3x3 le agrego una dimension


tensor([[0.0132, 0.2502, 0.7739],
        [0.2525, 0.4734, 0.7121],
        [0.0961, 0.8031, 0.9265]])

In [ ]:
'usamos -1 para asignar todos los valores restantes a una dimension'
x.view(-1).shape 


In [ ]:
'tensor a array'
x.numpy()


array([[0.01320934, 0.2501638 , 0.7739071 ],
       [0.25250095, 0.47338837, 0.71206266],
       [0.09609258, 0.8030895 , 0.92649555]], dtype=float32)

# **AUTOGRAD**

In [ ]:
x= torch.tensor(1.,requires_grad=True)
y= torch.tensor(2.,requires_grad=True)
p= x+y

z = torch.tensor(3.,requires_grad=True)

g = p * z


In [ ]:
g.backward()

In [ ]:
z.grad

tensor(3.)

In [ ]:
x.grad

tensor(3.)

In [ ]:
y.grad

tensor(3.)

# ***`COmpraobando Gpu`***

In [ ]:
'comprobar que podemos usar gpu'
import torch
torch.cuda.is_available()


True

In [ ]:
x= torch.randn(10000,10000)
y= torch.randn(10000,10000)

%time z= x*y   #get time on multiplication both matrice 

CPU times: user 122 ms, sys: 924 µs, total: 122 ms
Wall time: 122 ms


In [ ]:
x= torch.randn(10000,10000).cuda()
y= torch.randn(10000,10000).cuda()

%time z= x*y   #get time on multiplication both matrice CON GPU

CPU times: user 0 ns, sys: 3.94 ms, total: 3.94 ms
Wall time: 11.4 ms


In [ ]:
'enviando datos a la Gpu varias formas'

device = torch.device("cuda") '1'
x = torch.rand((10000,10000),device = "cuda")'1'

x=x.cuda() '2'

x=x.("cuda") '3'

x= x.to(device) '4'
