In [4]:
import numpy as np

l=[i for i in range(1000000)]


%time l2=[2*1 for i in l]


CPU times: user 291 ms, sys: 51.4 ms, total: 343 ms
Wall time: 341 ms


In [5]:
#realizanco con numpy
a = np.array(l)

% time a2= 2*a



CPU times: user 1.92 ms, sys: 17 ms, total: 18.9 ms
Wall time: 18.9 ms


In [6]:
#crear un vector de ceros
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [7]:
#crear matriz de zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
#tensor  de unos
a= np.ones((3,4,2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
#numero de elementos en cada dimension
a.shape

(3, 4, 2)

In [10]:
#longitud del nrray
a.ndim

3

In [11]:
# elementos totales en el array

a.size #3*4*2

24

In [13]:
l = [[1,2,3],[4,5,6]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
#vectir de int en rango
np.arange(1,5)

array([1, 2, 3, 4])

In [15]:
#vector de float
np.linspace(0,1,10) #entre 0 y uno dame 10 valores

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
#inicializando matrizes ramdon
np.random.rand(3,4)

array([[0.30106867, 0.80175513, 0.85349048, 0.19428287],
       [0.50442692, 0.69411142, 0.56252986, 0.70645189],
       [0.75775852, 0.48793835, 0.58093746, 0.54206369]])

In [17]:
a = np.arange(1,5)
a
#acceder al tipo de datos
a.dtype


dtype('int64')

In [ ]:
#creadno un aray de un tipo en especifico
a= np.arange(1,5,dtype=np.uint8)
a



lista de tipo devariables 
int8
int16
int32
int64
uint16
uint32
uint64,
float16,32,64
complex64,128


In [18]:
#vector
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#convertir un vector en matriz

a2=a.reshape(2,5) # las dimensiones tiene que coincidir




In [21]:
a=np.array([14,23,32,41])
b= np.array([5,4,3,2])



a+b




array([ 2.8       ,  5.75      , 10.66666667, 20.5       ])

In [22]:
a-b


array([ 9, 19, 29, 39])

In [23]:
a*b


array([70, 92, 96, 82])

In [24]:
a/b

array([ 2.8       ,  5.75      , 10.66666667, 20.5       ])

In [26]:
#accediendo a ciertos valores
a= np.array([1,5,3,19,13,7,3])

In [27]:
#acceder a un valor por su indice
a[3]

19

In [30]:
#troceado
a[2:5]  #de 2 a 5 sin incluir


array([ 3, 19, 13])

In [32]:
a[2:-1] #desde el segundo valor hasta el penultimo

array([ 3, 19, 13,  7])

In [33]:
#indexar valores ne matrices
b=np.arange(48).reshape(4,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [34]:
#indexar matriz, valor en segunda fila 3 columna

b[1,2] #acuerdate que empieza siempre en 0 por tanto es 2 3 en realidad

14

In [40]:
#INDEXADO FANCY

b[(0,2),2:4] #Cuidado


array([[ 2,  3],
       [26, 27]])

In [ ]:
#index bolleano
a=np.array([1,2,3,4]) ##ojo con esto
mask = np.array([True,False,True,False])
a[mask]

In [42]:
#iterando un array
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [43]:
for i in a:
  print(i)

0
1
2
3
4


In [55]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
for fila in a:
    for i in fila: #exclusivamente fila
        print(i)

0
1
2
3
4
5
6
7
8


In [61]:
#guardanto en archivo

np.save("mi_array.npy",a)


In [62]:
#cargando el  array
b=np.load("mi_array.npy")
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
#guardando arrays en un comprimido 1 solo archivo

a= np.arange(9).reshape((3,3))
b= np.arange(9).reshape((3,3))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
#guardar arrays
np.savez("mis_arrays",a=a,b=b)


In [68]:
#cargar arrays
mis_arrays= np.load("mis_arrays.npz")
mis_arrays